[workspace]
resolver = "2"
members = ["crates/vizzle-core", "crates/vizzle-py"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/stiproot/vizzle"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"

[profile.release]
lto = "thin"
codegen-units = 1
